export const availableCities = [
  'Aparecida de Goiânia - GO',
  'Barbacena - MG',
  'Belford Roxo - RJ',
  'Belo Horizonte - MG',
  'Bento Gonçalves - RS',
  'Blumenau - SC',
  'Boa Vista - RR',
  'Brasília - DF',
  'Campina Grande - PB',
  'Campinas - SP',
  'Campo Grande - MS',
  'Campos dos Goytacazes - RJ',
  'Caxias do Sul - RS',
  'Chapecó - SC',
  'Curitiba - PR',
  'Criciúma - SC',
  'Espera Feliz - MG',
  'Florianópolis - SC',
  'Fortaleza - CE',
  'Foz do Iguaçu - PR',
  'Goiânia - GO',
  'Guarulhos - SP',
  'Hortolândia - SP',
  'Indaial - SC',
  'Itaituba - PA',
  'Joaçaba - SC',
  'João Pessoa - PB',
  'Joinville - SC',
  'Lages - SC',
  'Leme - SP',
  'Marília - SP',
  'Maringá - PR',
  'Natal - RN',
  'Niterói - RJ',
  'Osasco - SP',
  'Ouro Preto - MG',
  'Parnaíba - PI',
  'Porto Alegre - RS',
  'Paulista - PE',
  'Recife - PE',
  'Ribeirão Preto - SP',
  'Rio de Janeiro - RJ',
  'Rio Branco - AC',
  'Salvador - BA',
  'Salto Grande - SP',
  'Santa Cruz do Sul - RS',
  'Santo André - SP',
  'Santo Antônio de Jesus - BA',
  'São João do Triunfo - PR',
  'São José - SC',
  'São Lourenço da Mata - PE',
  'São Paulo - SP',
  'São Vicente - SP',
  'Sapucaia do Sul - RS',
  'Uberlândia - MG',
  'Vitória - ES',
];

export const availableTechnologies = [
  '.NET',
  '.NET Core',
  'ASP',
  'ASP.NET',
  'ASP.NET Core',
  'AWS',
  'AWS EC2 (Elastic Compute Cloud)',
  'AWS RDS (Relational Database Service)',
  'AWS Redshift',
  'AWS S3',
  'AWS SQS (Simple Queue Service)',
  'Actionscript',
  'AdonisJS',
  'Ajax',
  'Angular 2',
  'Angular 7',
  'Angular 8',
  'Angular 9',
  'Angular 10',
  'AngularJS',
  'Apache',
  'Arquitetura SOA',
  'Arquitetura de software',
  'Azure',
  'Bash',
  'BigData',
  'Blender',
  'Blockchain',
  'Bootstrap',
  'C',
  'C#',
  'C++',
  'COBOL',
  'CSS',
  'CSS3',
  'CakePHP',
  'Clipper',
  'Continuous Integration/Deployment(CI/CD)',
  'Cultura Ágil',
  'Data Mining',
  'Data science',
  'Delphi',
  'Design Thinking',
  'Django',
  'Docker',
  'EJB',
  'ETL',
  'Eclipse',
  'Elasticsearch',
  'Elixir',
  'ExpressJS',
  'Firebase',
  'Firebird',
  'Flask',
  'Flutter',
  'Fortran',
  'Gestão',
  'Git',
  'Go',
  'Google Cloud',
  'Gulp',
  'HTML',
  'HTML5',
  'Hadoop',
  'Hibernate',
  'Hive',
  'Ionic',
  'JAVA EE ',
  'JIRA',
  'JPA',
  'JSF',
  'JSON',
  'JSP',
  'jQuery',
  'JUnit',
  'Java',
  'Java (Android)',
  'JavaScript',
  'Jenkins ',
  'Kanban',
  'Keras',
  'Kotlin',
  'Laravel 5',
  'Linux',
  'liquibase',
  'MATLAB',
  'Machine learning',
  'Maven',
  'Meteor ',
  'MongoDB',
  'MySQL',
  'NPM',
  'NestJS',
  'Nginx',
  'Node.js',
  'Nosql',
  'ORACLE',
  'Objective-C (iOS)',
  'PHP',
  'PL/SQL',
  'PhoneGap',
  'PostgreSQL',
  'Power BI',
  'Primefaces',
  'Python',
  'Programação Orientada a Objeto',
  'QT',
  'R -  language',
  'RESTful',
  'React',
  'React Native',
  'Redis',
  'Responsive\t Design',
  'Ruby',
  'Ruby on Rails',
  'SCRUM',
  'SQL',
  'SQL Server',
  'SVN',
  'Sass',
  'Scala',
  'SharePoint',
  'Shell Script',
  'Spark',
  'Spring',
  'Spring Boot',
  'SqLite',
  'Struts',
  'Swift (iOS)',
  'Symfony 2',
  'TDD',
  'TensorFlow',
  'Testes automatizados',
  'Tomcat',
  'Transact-SQL',
  'TypeScript',
  'UML',
  'Unity',
  'Unity3D',
  'Unreal Engine',
  'VBA',
  'Visual Basic',
  'Visual Basic .NET',
  'Visual Fox Pro',
  'Visual Studio',
  'Vue.js',
  'WCF- Windows Communication Foundation',
  'Web Services',
  'WordPress',
  'Xamarin',
  'Zend 2',
];
