export const availableCities = [
  'Aparecida de Goiânia - GO',
  'Barbacena - MG',
  'Belford Roxo - RJ',
  'Belo Horizonte - MG',
  'Bento Gonçalves - RS',
  'Blumenau - SC',
  'Boa Vista - RR',
  'Brasília - DF',
  'Campina Grande - PB',
  'Campinas - SP',
  'Campo Grande - MS',
  'Campos dos Goytacazes - RJ',
  'Caxias do Sul - RS',
  'Chapecó - SC',
  'Curitiba - PR',
  'Criciúma - SC',
  'Espera Feliz - MG',
  'Florianópolis - SC',
  'Fortaleza - CE',
  'Foz do Iguaçu - PR',
  'Goiânia - GO',
  'Guarulhos - SP',
  'Hortolândia - SP',
  'Indaial - SC',
  'Itaituba - PA',
  'Joaçaba - SC',
  'João Pessoa - PB',
  'Joinville - SC',
  'Lages - SC',
  'Leme - SP',
  'Marília - SP',
  'Maringá - PR',
  'Natal - RN',
  'Niterói - RJ',
  'Osasco - SP',
  'Ouro Preto - MG',
  'Parnaíba - PI',
  'Porto Alegre - RS',
  'Paulista - PE',
  'Recife - PE',
  'Ribeirão Preto - SP',
  'Rio de Janeiro - RJ',
  'Rio Branco - AC',
  'Salvador - BA',
  'Salto Grande - SP',
  'Santa Cruz do Sul - RS',
  'Santo André - SP',
  'Santo Antônio de Jesus - BA',
  'São João do Triunfo - PR',
  'São José - SC',
  'São Lourenço da Mata - PE',
  'São Paulo - SP',
  'São Vicente - SP',
  'Sapucaia do Sul - RS',
  'Uberlândia - MG',
  'Vitória - ES',
];
